# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [5]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print('list(a):', list(a) )
print('tolist():', a.tolist())

list(a)結果有顯現出屬性 array
a.tolist() 則沒有

list(a): [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist(): [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件
import numpy as np

In [8]:

a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[4 2 2 0 1 3]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [14]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[4 6 8 4]
 [8 2 2 4]
 [6 3 2 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [15]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[9 8]
  [4 4]
  [8 7]]

 [[2 9]
  [9 3]
  [9 8]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [28]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))
print(type(a))

[3, 5, 7, 6, 0, 9]
[3, 5, 7, 6, 0, 9]
<class 'numpy.ndarray'>


In [30]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))
print(b)

[[9, 3, 8, 6], [9, 8, 6, 0], [1, 5, 9, 1]]
[array([9, 3, 8, 6]), array([9, 8, 6, 0]), array([1, 5, 9, 1])]
[[9 3 8 6]
 [9 8 6 0]
 [1 5 9 1]]


In [25]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[7, 5], [0, 7], [7, 8]], [[0, 0], [0, 4], [5, 5]]]
[array([[7, 5],
       [0, 7],
       [7, 8]]), array([[0, 0],
       [0, 4],
       [5, 5]])]


In [31]:
def tolist(iterable):


print(tolist(a))
print(tolist(b))
print(tolist(c))


[[9, 3, 8, 6], [9, 8, 6, 0], [1, 5, 9, 1]]
[[array([7, 5]), array([0, 7]), array([7, 8])], [array([0, 0]), array([0, 4]), array([5, 5])]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


01Homework_維元.ipynb    基本題/                  範例程式.ipynb
Day_001_HW.ipynb         延伸題/
Numpy_practice.ipynb     作業解答.ipynb
